### ISSUE TITLE
Artist and album are not recognised

### ISSUE THREAD

**Issue by FoobarSven** [ghDaYuYu/foo_discogger#111]
Artist and album are not recognised although they are listed on discoggs, for example "Brothers Of Sword - The Brothers Still March" and "Burning Sun - Wake of Ashes".

**Comment by bassstorm** [comment]
Please have a look discussion in #110. Seems you came across the same use case.

**Comment by frogworth** [comment]
From that ticket, I'd note:
Open profile > foo_discogger-cache > artists, search for folder 7903888 and delete it if it is still there.

I've found that the disk cache is not deleted even if you clear all caches in the options.
In your case the artist IDs are 4669168 and 12380455.

If you poll the API directly, you can see the albums turn up - e.g. for Wake of Ashes:
https://api.discogs.com/artists/12380455/releases
That's pulling the releases for Burning Sun, and the master release for Wake of Ashes is shown.

**Comment by ghuDaYuYu** [comment]
Sorry for the late response...

> I've found that the disk cache is not deleted even if you clear all caches in the options.
In your case the artist IDs are 4669168 and 12380455

If by 'in the options' you mean the four buttons in the cache tab (Releases, Artists, Master Releases and Collection), you are right they do not delete the disk cache, just the memory cache.
Maybe disabling the 'Write' and 'Read' disk cache options might also help in troubleshooting this type of issue... and adding a new shortcut to open disk cache folders in Explorer from the Artist list and Release tree context menu would be helpful.
The original idea was to have some sort of assistance notifying server updates, still unsure about how to implement it and how much priority should it be given.

**Comment by ghuDaYuYu** [comment]
I agree with you, next release will be introducing disk cache expiration dates.
This is a draft of changes that might include:
- a. New toggle/field 'Disk cache expiration days' added to the preferences panel 'Cache' tab.
- b. When an entity is successfully cached (artist, artist releases, release...), a file 'taskreg.txt' is created in its folder, containing:

line 1: 2017-06-30T01:42:35-07:00 2022-03-21T09:14:42-07:00 -> in releases, otherwise '\n'
line 2: 2024-08-27T11:55:20+0200 2024-09-26T11:55:20+0200

First line: Discogs release creation and Discogs last modification date
Second line: Discogger disk cache creation and expiration date

- c. Successive access to releases will reload them from the server if they expired.

I am still unsure if all 'artist releases' should also expire when the artist itself expires,
or if just one of its releases expired.
I'd also like that some artists with huge album collections could never expire. 

Python scripts would also come in handy removing expired cache items from the command prompt.

Thanks a lot for your suggestion about the expiration date, please feel free to continue with the discussion if you have further ideas about implementing this feature or provide further comments or test reports on next release.

**Comment by ghuDaYuYu** [comment]
Hi there!
Here is a new beta release... in case someone would like to give it try...

v.1.0.21 Beta 1
- Introducing disk cache expiration days. Expiration does not affect the Memory cache yet. There might be a new checkbox 'Also update expired from item in memory cache'.
- $filter function not taking arrays as second parameter.
- General revision of all UTF paths.
- Thumbnail cache expiring dates not implemented.
- No feature to delete expired item from the cache folder yet.
- CONFIG FILE NOT BACKWARD COMPATIBLE WITH EARLIER VERSION.

Please backup your foo_discogger.cfg file before installing.

[foo_discogger 1.0.21 Beta 1](https://github.com/user-attachments/files/16825446/foo_discogger.1.0.21.Beta.1.zip)

**Comment by bassstorm** [comment]
Hello @ghuDaYuYu!
Thanks for quick turnaround. Got a few questions.

> I am still unsure if all 'artist releases' should also expire when the artist itself expires,
> or if just one of its releases expired.
> I'd also like that some artists with huge album collections could never expire.

I think cascade expiration makes sense. What's important here is that newly created releases should be retrievable sooner than later.

And second question, I don't see this feature mentioned in v1.0.21 release notes. Shall I deal with above betas to test?

**Comment by ghuDaYuYu** [comment]
Hi there!
I am afraid there has been no progress related to the cache expiration feature.
But you may continue testing with [foo_discogger 1.0.21.2 Beta 1](https://gist.github.com/ghuDaYuYu/c4f4c4952e6b2ec3a8101027104eef08/raw/a9e3b4a4dbcf188a8dcfa9aba0cac3eb64871d14/foo_discogger%25201.0.21.2%2520Beta%25201.zip).
The beta feature ['search artist + master title'](https://github.com/ghDaYuYu/foo_discogger/discussions/117) is also included.

**Comment by bassstorm** [comment]
Thanks, will give it some time throughout the weeked. Will keep you posted on results.

**Comment by ghuDaYuYu** [comment]
You are welcome... thanks to you also for testing.

> I think cascade expiration makes sense. What's important here is that newly created releases should be retrievable sooner than later.
 
That sounds a bit aspiring : )
For instant updates there is an option to disable the 'disk cache' or 'read disk cache'.
Although, cleaning the memory cache will still be required. Although I only ran very rudimentary tests at the time.
Nice weekend, regards!

**Comment by ghuDaYuYu** [comment]
Fixed release binary...

[foo_discogger 1.0.21.2 Beta 2.zip](https://gist.github.com/ghuDaYuYu/ff61eec25be11fa8ee7dea29c5621def/raw/8c38ada6e646670f4444ba9f87c2c4c16d4d0531/foo_discogger%25201.0.21.2%2520Beta%25202.zip)

**Comment by ghuDaYuYu** [comment]
Fixed expiration day check (expired = difference + cfg.days <=0)
[foo_discogger 1.0.21.2 Beta 3.zip](https://gist.github.com/ghuDaYuYu/54b1d80c84c620c32831711ab70ced06/raw/86f605a0886581846cf9b11ac61c66f1e0d7bd32/foo_discogger%25201.0.21.2%2520Beta%25203.zip)

**Comment by ghuDaYuYu** [comment]
I believe we should continue this topic in 'Discussions'.
I am closing the issue as [frogworth](https://github.com/frogworth) already provided a way to solve it.
Thanks for you feedback!
