### ISSUE TITLE
Missing release artwork

### ISSUE THREAD

**Issue by Klaster1** [ghDaYuYu/foo_discogger#123]
First of all, thanks for the extension fork that fixes the JSON parsing issue.

I noticed that the release artwork's not being loaded. Maybe I misconfigured something? See details in the video below.

https://github.com/user-attachments/assets/939c7dbe-bd88-40b7-872f-57607d52a2bf

**Comment by ghuDaYuYu** [comment]
You are welcome, thank you also for reporting this bug.
Sorry about the inconvenience, unfortunately I am finding it hard to set time aside for testing and developing lately.
I believe the issue is not related to some misconfiguration on your side but to v1.0.21.x public releases.
If you do not mind running a beta release, [v1.0.21.2 Beta 6](https://gist.github.com/ghuDaYuYu/9c463859efbb5640fa01b0f3a685eb88/raw/9d6e37c402b7c468a4efdf7752ae640b0c5065ee/foo_discogger%25201.0.21.2%2520Beta%25206.zip) should fix this issue...

![test Juno](https://github.com/user-attachments/assets/3aa513d6-731b-4d95-bf5f-087a7ccd2e9d)

If you rather prefer avoiding beta releases another option would be to downgrade to [v1.0.20.5](https://github.com/ghDaYuYu/foo_discogger/releases/tag/v1.0.20.5). Note that downgrading from v1.0.21 to v1.0.20.x requires overwriting the config file with a previously backed-up v1.0.20.x config, otherwise configuration will be reset. If a config backup is not available, you could install a fresh portable fb2k with discogger v1.0.20.5 first, then copy over v1.0.21.1 preference settings to recreate a v1.0.20.5 compatible foo_discogger.dll.cfg.

Hopefully, a new public release will be available before Xmas fixing this issue.

**Comment by Klaster1** [comment]
With the linked beta build, I foo_discogger indeed managed to add a front cover to the release I showcased above. Thank you again!

**Comment by ghuDaYuYu** [comment]
Glad it worked, thanks for testing!
